@extends('layouts.app')
@section('content')
	<div class="col-md-10 col-md-offset-1">
		<p dir="ltr" style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 28px; font-family: Verdana; color: #000000; vertical-align: baseline; white-space: pre-wrap; background-color: transparent;">Privacy Policy</span></p>
		<p>&nbsp;</p>
		<p dir="ltr" style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 14.6667px; font-family: Arial; color: #000000; vertical-align: baseline; white-space: pre-wrap; background-color: transparent;">Robodoo (also referenced below as &ldquo;We&rdquo;, &ldquo;us&rdquo;, &ldquo;our&rdquo; or &ldquo;the Company&rdquo;) is committed to safeguard the privacy of our website visitors. This Privacy Policy explains the information we gather so that you may easily understand the way in which we protect your personal information and other related details. By using our services, you acknowledge that you have reviewed this Privacy Policy and agree to be bound by our terms and conditions. </span></p>
		<p>&nbsp;</p>
		<p dir="ltr" style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 14.6667px; font-family: Arial; color: #000000; font-weight: bold; vertical-align: baseline; white-space: pre-wrap; background-color: transparent;">PERSONAL INFORMATION</span></p>
		<p>&nbsp;</p>
		<p dir="ltr" style="line-height: 1.8; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 14.6667px; font-family: Roboto; color: #555555; vertical-align: baseline; white-space: pre-wrap;">When you use our services, you trust us with your data. It is our responsibility to be clear about what we collect and how we use it to make our services work better for you.</span></p>
		<p dir="ltr" style="line-height: 1.8; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 14.6667px; font-family: Roboto; color: #555555; vertical-align: baseline; white-space: pre-wrap;">Here are the main types of data we collect:</span></p>
		<ul style="margin-top: 0pt; margin-bottom: 0pt;">
			<li dir="ltr" style="list-style-type: disc; font-size: 14.6667px; font-family: Roboto; color: #555555; vertical-align: baseline;">
				<p dir="ltr" style="line-height: 1.8; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 14.6667px; vertical-align: baseline; white-space: pre-wrap;">1</span></p>
			</li>
			<li dir="ltr" style="list-style-type: disc; font-size: 14.6667px; font-family: Roboto; color: #555555; vertical-align: baseline;">
				<p dir="ltr" style="line-height: 1.8; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 14.6667px; vertical-align: baseline; white-space: pre-wrap;">2</span></p>
			</li>
			<li dir="ltr" style="list-style-type: disc; font-size: 14.6667px; font-family: Roboto; color: #555555; vertical-align: baseline;">
				<p dir="ltr" style="line-height: 1.8; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 14.6667px; vertical-align: baseline; white-space: pre-wrap;">3</span></p>
			</li>
			<li dir="ltr" style="list-style-type: disc; font-size: 14.6667px; font-family: Roboto; color: #555555; vertical-align: baseline;">
				<p dir="ltr" style="line-height: 1.8; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 14.6667px; vertical-align: baseline; white-space: pre-wrap;">4</span></p>
			</li>
			<li dir="ltr" style="list-style-type: disc; font-size: 14.6667px; font-family: Roboto; color: #555555; vertical-align: baseline;">
				<p dir="ltr" style="line-height: 1.8; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 14.6667px; vertical-align: baseline; white-space: pre-wrap;">5</span></p>
			</li>
		</ul>
		<p>&nbsp;</p>
		<p dir="ltr" style="line-height: 1.8; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 14.6667px; font-family: Roboto; color: #555555; font-weight: bold; vertical-align: baseline; white-space: pre-wrap;">USING OF INFORMATION</span></p>
		<p>&nbsp;</p>
		<p dir="ltr" style="line-height: 1.8; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 14.6667px; font-family: Roboto; color: #555555; vertical-align: baseline; white-space: pre-wrap;">We use the information and data we collect in connection with operation, maintenance and enhancement of our services and features, and for other administrative purposes or internal operations, such as communicating with our users, data analysis, testing and research. In addition, We may use the information and data we collect about you in order to measure and understand the effectiveness of our ads and other content and offer you tailored content, like giving you more relevant ads. For example, your birthday, gender and other demographic characteristics allow us to show you age-appropriate and gender-related content and advertisements. We may also examine and analyze your feedback and answers to the quizzes in our WebSite to serve ads that you may enjoy or find interesting. For example, if a user participates in content around new model cars, We may infer that this user is planning to purchase a new vehicle or that he/she recently purchased a new vehicle. Alternatively, if a user indicates in a quiz that he/she enjoys baseball, We may infer this user is a sport fan. Advertisers of either automotive or sports products may ask us to display advertisements to individuals that have an affinity towards their products. </span></p>
		<p>&nbsp;</p>
		<p dir="ltr" style="line-height: 1.8; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 14.6667px; font-family: Roboto; color: #000000; font-weight: bold; vertical-align: baseline; white-space: pre-wrap;">SHARING OF INFORMATION</span></p>
		<p>&nbsp;</p>
		<p dir="ltr" style="line-height: 1.8; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 14.6667px; font-family: Roboto; color: #000000; vertical-align: baseline; white-space: pre-wrap;">Robodoo will not sell user&rsquo;s information to a third party. Unless it is required to do so by law or</span></p>
		<p dir="ltr" style="line-height: 1.8; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 14.6667px; font-family: Roboto; color: #000000; vertical-align: baseline; white-space: pre-wrap;">Government authority.</span></p>
		<p>&nbsp;</p>
		<p dir="ltr" style="line-height: 1.8; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 14.6667px; font-family: Arial; color: #000000; font-weight: bold; vertical-align: baseline; white-space: pre-wrap; background-color: transparent;">THIRD-PARTY LINKS</span></p>
		<p>&nbsp;</p>
		<p dir="ltr" style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 14.6667px; font-family: Arial; color: #000000; vertical-align: baseline; white-space: pre-wrap; background-color: transparent;">Occasionally, at our discretion, we may include or offer third-party products or services on our website. These third-party sites have separate and independent privacy policies. We therefore have no responsibility or liability for the content and activities of these linked sites. Nonetheless, we seek to protect the integrity of our site and welcome any feedback about these sites.</span></p>
		<p>&nbsp;</p>
		<p dir="ltr" style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 14.6667px; font-family: Arial; color: #000000; font-weight: bold; vertical-align: baseline; white-space: pre-wrap; background-color: transparent;">GOOGLE REMARKETING</span></p>
		<p>&nbsp;</p>
		<p dir="ltr" style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 14.6667px; font-family: Arial; color: #000000; vertical-align: baseline; white-space: pre-wrap; background-color: transparent;">Google's advertising requirements can be summed up by Google's Advertising Principles. They are put in place to provide a positive experience for users. </span><a style="text-decoration: none;" href="https://support.google.com/adwordspolicy/answer/1316548?hl=en" target="_blank" data-saferedirecturl="https://www.google.com/url?hl=en&amp;q=https://support.google.com/adwordspolicy/answer/1316548?hl%3Den&amp;source=gmail&amp;ust=1469528542929000&amp;usg=AFQjCNEcW4RwOpmZNahxVhFpKnVpzZ4gSQ"><span style="font-size: 14.6667px; font-family: Arial; text-decoration: underline; vertical-align: baseline; white-space: pre-wrap; background-color: transparent;">https://support.google.com/<wbr />adwordspolicy/answer/1316548?<wbr />hl=en </span></a></p>
		<p dir="ltr" style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 14.6667px; font-family: Arial; color: #000000; vertical-align: baseline; white-space: pre-wrap; background-color: transparent;">We use Google AdSense Advertising on our website.</span></p>
		<p>&nbsp;</p>
		<p dir="ltr" style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 14.6667px; font-family: Arial; color: #000000; vertical-align: baseline; white-space: pre-wrap; background-color: transparent;">Google, as a third-party vendor, uses cookies to serve ads on our site. Google's use of the DART cookie enables it to serve ads to our users based on previous visits to our site and other sites on the Internet. Users may opt-out of the use of the DART cookie by visiting the Google Ad and Content Network privacy policy.</span></p>
		<p>&nbsp;</p>
		<p dir="ltr" style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 14.6667px; font-family: Arial; color: #000000; font-weight: bold; vertical-align: baseline; white-space: pre-wrap; background-color: transparent;">SECURITY</span></p>
		<p dir="ltr" style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 14.6667px; font-family: Arial; color: #000000; font-weight: bold; vertical-align: baseline; white-space: pre-wrap; background-color: transparent;"><br /></span><span style="font-size: 14.6667px; font-family: Arial; color: #000000; vertical-align: baseline; white-space: pre-wrap; background-color: transparent;">All information described above may be stored on database servers. We will take commercially reasonable measures in providing secure transmission of your Personal Information before it is transferred across the internet from your system to our servers and in securing such Personal Information stored on our systems. However, you should be aware that there is always some risk involved in transmitting information over the internet and that there is also some risk that others could find a way to thwart our security systems. As a result, while we strive to protect your Personal Information, We cannot ensure or warrant the security and privacy of your Personal Information or other content you transmit using Robodoo, and you do so at your own risk. Thus, We encourage you to exercise discretion regarding the Personal Information you choose to disclose to us.</span></p>
		<p>&nbsp;</p>
		<p dir="ltr" style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 14.6667px; font-family: Arial; color: #000000; font-weight: bold; vertical-align: baseline; white-space: pre-wrap; background-color: transparent;">PRIVACY POLICY UPDATES</span></p>
		<p dir="ltr" style="line-height: 1.38; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 14.6667px; font-family: Arial; color: #000000; font-weight: bold; vertical-align: baseline; white-space: pre-wrap; background-color: transparent;"><br /></span><span style="font-size: 14.6667px; font-family: Arial; color: #000000; vertical-align: baseline; white-space: pre-wrap; background-color: transparent;">Robodoo reserves the right to amend or update this Privacy Policy from time to time, with or without notice. In such case, we will post the updated Privacy Policy on its Website. We encourage you to review this Privacy Policy regularly for any changes. Your continued use of our services will be subjected to the then-current privacy policy. If any modification is unacceptable to you, you may cease using our services. If you do not cease using our services, you will be deemed to have accepted the new Privacy Policy updates.</span></p>
	</div>
@endsection